// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Domain.Models;

namespace Infra.Mapping
{
    public class NivelConfiguration : IEntityTypeConfiguration<Nivel>
    {
        public void Configure(EntityTypeBuilder<Nivel> entity)
        {
            entity.HasKey(x => x.NivelId);
            entity.HasOne<Pontuacao>()
                        .WithOne(x => x.Nivel)
                        .HasForeignKey<Pontuacao>(x => x.NivelId);

        }
    }
}
