// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Domain.Models;

namespace Infra.Mapping
{
    public class NivelConfiguration : IEntityTypeConfiguration<Nivel>
    {
        public void Configure(EntityTypeBuilder<Nivel> entity)
        {
            entity.HasKey(x => x.NivelId);

            entity.HasOne(d => d.Pontuacao)
                .WithMany(p => p.Nivel)
                .HasForeignKey(d => d.PontuacaoId)
                .HasConstraintName("FK_Nivel_Pontuacao");
        }
    }
}
