// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Domain.Models;

namespace Infra.Mapping
{
    public class PerguntaConfiguration : IEntityTypeConfiguration<Pergunta>
    {
        public void Configure(EntityTypeBuilder<Pergunta> entity)
        {
            entity.HasKey(x => x.PerguntaId);          

            entity.HasOne(x=>x.Quizz).WithMany(x=>x.Pergunta)
                    .HasConstraintName("Pergunta_Quizz_Id");

                  //  entity.HasOne(x=>x.EstudanteResposta).WithOne(x=>x.)
        }
    }
}
