// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Domain.Models;

namespace Infra.Mapping
{
    public class ProfessorConfiguration : IEntityTypeConfiguration<Professor>
    {
        public void Configure(EntityTypeBuilder<Professor> entity)
        {
            entity.HasKey(x => x.ProfessorId);
            entity.HasOne(x => x.Quizz).WithOne(x => x.Professor).HasForeignKey<Quizz>(x => x.ProfessorId);
        }
    }
}