// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Domain.Models;

namespace Infra.Mapping
{
    public class QuizzConfiguration : IEntityTypeConfiguration<Quizz>
    {
        public void Configure(EntityTypeBuilder<Quizz> entity)
        {
            entity.HasKey(x => x.QuizzId);
            entity.HasOne(x => x.Professor)
                    .WithOne(x => x.Quizz)
                    .HasForeignKey<Professor>(x => x.ProfessorId);

        }
    }
}
