// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public class Estudante
    {
        public Estudante()
        {
            Resposta = new HashSet<Resposta>();
        }

        public int EstudanteId { get; set; }
        public string EstudanteSessao { get; set; }

        public virtual ICollection<Resposta> Resposta { get; set; }

        public decimal Pontuacao { get; set; }
    }
}