// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.DTO;
using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public class Estudante
    {
      

        public int EstudanteId { get; set; }
        public string EstudanteSessao { get; set; }
        public string Nome { get; set; }
        public virtual IEnumerable<EstudanteResposta> Respostas { get; set; }

        public decimal Pontuacao { get; set; }
    }
}