// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public class Pergunta
    {
        public int PerguntaId { get; set; }
        public int? NivelId { get; set; }
        public int? RespostaId { get; set; }
        public int? QuizzId { get; set; }
        public string OpcaoA { get; set; }
        public string OpcaoB { get; set; }
        public string OpcaoC { get; set; }
        public string OpcaoD { get; set; }
        public string Descricao { get; set; }
        public string OpcaoCerta { get; set; }

        public virtual Nivel Nivel { get; set; }
        public virtual Quizz Quizz { get; set; }
        public virtual Resposta Resposta { get; set; }
    }
}