// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public class Professor
    {

        public int ProfessorId { get; set; }
        public string ProfessorSessao { get; set; }

    }
}