// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public class Quizz
    {
        public Quizz()
        {
            Pergunta = new HashSet<Pergunta>();
        }

        public int QuizzId { get; set; }        public DateTime DataInclusao { get; set; }
        public string Descricao { get; set; }
        public bool Ativo { get; set; }
        public virtual ICollection<Pergunta> Pergunta { get; set; }
        public string ProfessorSessao { get; set; }

        public int ProfessorId { get; set; }

        //public virtual Professor Professor { get; set; }
    }
}