// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.DTO;
using System;
using System.Collections.Generic;

namespace Domain.Models 

{
    public class Resposta
    {
      
        public bool Acertou { get;set;}
        public int RespostaId { get; set; }
        public string EstudanteChave { get; set; }
        public string Descricao { get; set; }
        public virtual IEnumerable<EstudanteResposta> Estudante { get; set; }
        public virtual IEnumerable<Pergunta> Pergunta { get; set; }
        public int EstudanteId{get;set;}
        public int PerguntaId { get; set; }
        public int Valor { get; set; }

    }
}