// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20200812162752_45")]
    partial class _45
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Estudante", b =>
                {
                    b.Property<int>("Estudante_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Resposta_id")
                        .HasColumnType("int");

                    b.HasKey("Estudante_ID");

                    b.HasIndex("Resposta_id");

                    b.ToTable("Estudante");
                });

            modelBuilder.Entity("Domain.Models.Nivel", b =>
                {
                    b.Property<int>("Nivel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pontuacao_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Pontuacao_ID1")
                        .HasColumnType("int");

                    b.HasKey("Nivel_id");

                    b.HasIndex("Pontuacao_ID1");

                    b.ToTable("Nivel");
                });

            modelBuilder.Entity("Domain.Models.Pontuacao", b =>
                {
                    b.Property<int>("Pontuacao_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Pontuacao_ID");

                    b.ToTable("Pontuacao");
                });

            modelBuilder.Entity("Domain.Models.Professor", b =>
                {
                    b.Property<int>("Professor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Professor_ID");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("Domain.Models.Quizz", b =>
                {
                    b.Property<int>("Quiz_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataInclusão")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Professor_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Professor_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Turma_ID")
                        .HasColumnType("int");

                    b.HasKey("Quiz_id");

                    b.HasIndex("Professor_ID1");

                    b.ToTable("Quizz");
                });

            modelBuilder.Entity("Domain.Models.Resposta", b =>
                {
                    b.Property<int>("Resposta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Estudante_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Estudante_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Pergunta_id")
                        .HasColumnType("int");

                    b.Property<string>("RespostaCerta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Resposta_id");

                    b.HasIndex("Estudante_ID1");

                    b.HasIndex("Pergunta_id")
                        .IsUnique();

                    b.ToTable("Resposta");
                });

            modelBuilder.Entity("Domain.Pergunta", b =>
                {
                    b.Property<int>("Pergunta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nivel_id")
                        .HasColumnType("int");

                    b.Property<string>("OpcaoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcaoB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcaoC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcaoCerta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcaoD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuizzQuiz_id")
                        .HasColumnType("int");

                    b.Property<int>("Quizz_id")
                        .HasColumnType("int");

                    b.Property<int>("Resposta_id")
                        .HasColumnType("int");

                    b.HasKey("Pergunta_id");

                    b.HasIndex("Nivel_id");

                    b.HasIndex("QuizzQuiz_id");

                    b.ToTable("Pergunta");
                });

            modelBuilder.Entity("Domain.Models.Estudante", b =>
                {
                    b.HasOne("Domain.Models.Resposta", null)
                        .WithMany("Estudante_Reposta")
                        .HasForeignKey("Resposta_id");
                });

            modelBuilder.Entity("Domain.Models.Nivel", b =>
                {
                    b.HasOne("Domain.Models.Pontuacao", "Pontuacao")
                        .WithMany()
                        .HasForeignKey("Pontuacao_ID1");
                });

            modelBuilder.Entity("Domain.Models.Quizz", b =>
                {
                    b.HasOne("Domain.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("Professor_ID1");
                });

            modelBuilder.Entity("Domain.Models.Resposta", b =>
                {
                    b.HasOne("Domain.Models.Estudante", null)
                        .WithMany("Resposta_Estudante")
                        .HasForeignKey("Estudante_ID1");

                    b.HasOne("Domain.Pergunta", "Pergunta")
                        .WithOne("Resposta")
                        .HasForeignKey("Domain.Models.Resposta", "Pergunta_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Pergunta", b =>
                {
                    b.HasOne("Domain.Models.Nivel", "Nivel")
                        .WithMany("Perguntas")
                        .HasForeignKey("Nivel_id");

                    b.HasOne("Domain.Models.Quizz", "Quizz")
                        .WithMany("Perguntas")
                        .HasForeignKey("QuizzQuiz_id");
                });
#pragma warning restore 612, 618
        }
    }
}
